### ISSUE TITLE
バックテストでのエラー

### ISSUE THREAD

**Issue by Mega-Takoyaki** [unageanu/jiji2#128]
公開された手順通りにHerokuにインストールした直後、デフォルトの設定でバックテストを実行したのですが、エラーになってしまい下記のようなログが出ております。
何かやり方が間違っていますでしょうか？

> E, [2016-09-07T23:25:34.573397 #3] ERROR -- : undefined method `bid' for nil:NilClass (NoMethodError)
agent/moving_average_agent.rb:45:in `block in next_tick'
agent/moving_average_agent.rb:45:in `map'
agent/moving_average_agent.rb:45:in `next_tick'
/app/src/jiji/model/agents/agents.rb:35:in `block in next_tick'
/app/src/jiji/model/agents/agents.rb:33:in `each'
/app/src/jiji/model/agents/agents.rb:33:in `next_tick'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:17:in `exec'
/app/src/jiji/model/trading/jobs/notify_next_tick_job.rb:74:in `exec'
/app/src/jiji/model/trading/process.rb:37:in `do_next_job'
/app/src/jiji/model/trading/process.rb:30:in `run'
/app/src/jiji/model/trading/process.rb:24:in `block in start'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/app/vendor/bundle/ruby/2.2.0/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'

よろしくお願いします。

**Comment by unageanu** [comment]
おそらく、バックテストの設定で必要な通貨ペアがチェックされてないものと思われます。
標準添付の `MovingAverageAgent` は `:USDJPY` を利用しますので、バックテスト作成画面の「使用する通貨ペア」でこれをチェックして実行してみてください。

**Comment by Mega-Takoyaki** [comment]
ありがとうございます、実行できました。
AUDJPYにチェックしておりました。
お手数おかけしました。
