### ISSUE TITLE
spec の走らせ方について

### ISSUE THREAD

**Issue by tanukiti1987** [unageanu/jiji2#13]
今、手元で fork して spec を全部走らせてみたのですが、

https://github.com/unageanu/jiji2/blob/master/spec/jiji/db/v0to1/create_capped_collection_spec.rb#L43

だけ、必ず失敗してしまいます。

5つの `Jiji::Model::Notification::Notification` を作った後に、 3つの `Jiji::Model::Notification::Notification` レコードが存在することを確認していますが、どういう処理を行ったうえで、2つのオブジェクトが `count` の対象から外れる感じでしょうか。

issue に立てるべき内容かアヤシイですが、ご教授いただけると嬉しいです。

**Comment by tanukiti1987** [comment]
説明不足でした。 ログなどを貼ります。

jiji2 をフォークして、手元で `mongo` を起動した状態で以下のコマンドを叩いています。

```
$ bundle exec rspec spec/jiji/db/v0to1/create_capped_collection_spec.rb:28 -I src -I spec -I sample_agents/src -I sample_agents/spec -fdoc
/Users/USERNAME/work/jiji2/spec/jiji/test/configurations/coverage_configuration.rb:12:in `block in <top (required)>': [DEPRECATION] ::[] is deprecated. Use ::new instead.
Run options: include {:focus=>true, :locations=>{"./spec/jiji/db/v0to1/create_capped_collection_spec.rb"=>[28]}}

Jiji::Db::CreateCappedCollections
  #call (FAILED - 1)

Failures:

  1) Jiji::Db::CreateCappedCollections #call
     Failure/Error: expect(Jiji::Model::Notification::Notification.count).to be 3

       expected #<Fixnum:7> => 3
            got #<Fixnum:9> => 4

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/jiji/db/v0to1/create_capped_collection_spec.rb:43:in `check_notification_collection'
     # ./spec/jiji/db/v0to1/create_capped_collection_spec.rb:34:in `block (2 levels) in <top (required)>'

Finished in 0.37411 seconds (files took 1.5 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/jiji/db/v0to1/create_capped_collection_spec.rb:28 # Jiji::Db::CreateCappedCollections #call
```

**Comment by unageanu** [comment]
# 返信が遅くなり申し訳ありません。

おそらくNotificationコレクションが Capped Collection(既定サイズを超えるとデータが自動で削除されるコレクション) になっていないことが原因と思います。
以下をお試しください。

1. テスト用のdb(jiji_test)を一旦ドロップする。
2. create_capped_collection_spec.rb を個別に実行する

```
$ cd jiji2/
$ bundle rspec exec rspec -I src -I spec spec/jiji/db/v0to1/create_capped_collection_spec.rb
```

詳細:
create_capped_collection_spec.rb 内で、コレクションを capped_collection として作成する処理を行っているのですが、おそらく他のテストか何かを実行する際にコレクションが生成されてしまい、create_capped_collection_spec.rb 内での生成処理がスキップされてしまっているものと思われます。コレクションを一旦削除して、capped_collection として再作成すれば動作するようになるはずです。

**Comment by tanukiti1987** [comment]
jiji_test を削除したうえで、 L43 のテストだけを実行したら、通ることが確認できました。

`create_capped_collection_spec.rb` をファイルごと実行すると、

```
Jiji::Model::Trading::RMT balance_of_yesterday one_dayのデータから昨日の最新のデータが取得され、返却される
```

が失敗したり、成功したり。。といった感じですね。。 ひとまず解決しました！
丁寧なご回答ありがとうございました :bow:

**Comment by unageanu** [comment]
> Jiji::Model::Trading::RMT balance_of_yesterday one_dayのデータから昨日の最新のデータが取得され、返却される
> が失敗したり、成功したり。

情報ありがとうございます! 確認してみます。
