### ISSUE TITLE
OandaAPI::RequestError の例外処理を行う

### ISSUE THREAD

**Issue by tanukiti1987** [unageanu/jiji2#14]
OandaAPI からのレスポンスが帰ってこないとの例外処理を拾っていないため、アプリケーションが落ちてしまうようです。

https://github.com/unageanu/jiji2/blob/master/src/jiji/model/securities/internal/oanda/rate_retriever.rb#L19

該当行の処理に対して、 `OandaAPI::RequestError` に対する適切な例外を行う必要がありそうです。

以下、nginx に出ていたエラーログです。

```
W, [2016-03-06T04:27:16.940782 #1]  WARN -- : oanda_api: It took 31.944752034 seconds to obtain a connection.  Consider raising the pool size which is currently set to 2.
E, [2016-03-06T05:10:35.095800 #1] ERROR -- : An error as occured while processing response. Original Exception: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (OandaAPI::RequestError)
/usr/local/bundle/gems/oanda_api-0.9.4/lib/oanda_api/client/client.rb:119:in `rescue in execute_request'
/usr/local/bundle/gems/oanda_api-0.9.4/lib/oanda_api/client/client.rb:105:in `execute_request'
/usr/local/bundle/gems/oanda_api-0.9.4/lib/oanda_api/client/namespace_proxy.rb:107:in `method_missing'
/app/jiji2/src/jiji/model/securities/internal/oanda/rate_retriever.rb:19:in `retrieve_current_tick'
/app/jiji2/src/jiji/model/trading/brokers/abstract_broker.rb:30:in `tick'
/app/jiji2/src/jiji/model/trading/brokers/abstract_broker.rb:104:in `refresh'
/app/jiji2/src/jiji/model/trading/jobs/notify_next_tick_job.rb:22:in `before_do_next'
/app/jiji2/src/jiji/model/trading/jobs/notify_next_tick_job.rb:16:in `exec'
/app/jiji2/src/jiji/model/trading/process.rb:37:in `do_next_job'
/app/jiji2/src/jiji/model/trading/process.rb:30:in `run'
/app/jiji2/src/jiji/model/trading/process.rb:24:in `block in start'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:67:in `call'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'
```

**Comment by unageanu** [comment]
バックテストの処理中で発生した例外は、[process.rb:L38](https://github.com/unageanu/jiji2/blob/master/src/jiji/model/trading/process.rb#L38
)でキャッチしてログ出力した後、処理を継続するようにしているのですが、落ちてしまいましたか?

アプリ終了=jiji(puma)のプロセスが落ちる、という認識でよいでしょうか?

**Comment by tanukiti1987** [comment]
nginx の最後のログは issue に記載していたとおりでした。

サーバーのCPU負荷を見ているとちょうど 5:10 頃から、一気に負荷が下がっているので、このエラーを気に jiji(puma) が落ちたのかと推測してました。( 処理を継続するようにしているなら他の原因なのかもしれないですね。）

> アプリ終了=jiji(puma)のプロセスが落ちる

ですです。プロセス（docker のプロセス）まるごと落ちていたので、ちょっと手がかりが少ないですね。。他に必要そうな情報があれば教えてください :pray:

**Comment by unageanu** [comment]
インストール先は、Docker(AWS) または Heroku のどちらでしょうか?

**Comment by tanukiti1987** [comment]
GoogleCloudPlatform で  f1-micro（vCPU x 1、メモリ 0.6 GB）、 Debian jessie で試してます。

1年くらいのバックテストを動かそうとしていて、2度ほど起きた感じです。

**Comment by unageanu** [comment]
GoogleCloudPlatform は詳しくないのですが、何かのリミットに達している可能性はないでしょうか?
メモリが少なめなので、そのあたりとか。

**Comment by tanukiti1987** [comment]
> メモリが少なめなので、そのあたりとか。

これは十分にありそうですね。。 大きめのインスタンスを用意して試してみます。

**Comment by tanukiti1987** [comment]
メモリ4GBの環境で試してみたところ、安定して動いているみたいです。

コードの問題ではなさそうです。 お騒がせしました :bow:

**Comment by unageanu** [comment]
ひとまず、良かったです!
もし、長期間のバックテスト実行等でメモリリークする、みたいな問題があれば修正しますので、ご連絡ください。
