### ISSUE TITLE
jijiエージェントでのデバッグログの出力方法について

### ISSUE THREAD

**Issue by sugiare418** [unageanu/jiji2#340]
お世話になります。
表題の件、ご教示くださいませ。

現在の状況としては、
- エージェントに対してログ出力のコーディング実施
- エージェントの処理（バックテスト）は正常終了
- テスト一覧>ログを確認すると、「ログはありません」と表示される

以下、コードの一部を転記します
```ruby
require 'logger'
@logger = Logger.new(STDOUT)
@logger.level = Logger::DEBUG
@logger.debug '*** ログテスト ***'
```

jijiのバージョンは確認方法がわかりませんでしたが、
tensorflow連携サンプルのgitリポジトリをベースにしております。

以上、よろしくお願いいたします。

**Comment by unageanu** [comment]
ログ出力には、エージェントに設定されているロガーを使用してください
以下は、初期化後( `post_create` ) にログを出力するサンプルです。

```ruby
class SampleAgent
  include Jiji::Model::Agents::Agent
  
  def post_create
    logger.debug "test"
  end

end
```

**Comment by sugiare418** [comment]
早速のご回答ありがとうございます。
ログ出力できました。

当初、回答頂いた内容でも試してはいたのですが、
エージェントでは無いクラス（サンプルにあったSignalCalculatorクラス）で
ログを埋め込んでいたためエラーとなっしまっておりました。。。

ありがとうございました。
