### ISSUE TITLE
How does the future works?

### ISSUE THREAD

**Issue by janckerchen** [unageanu/jiji2#389]
I dont understand `invoke_on_rmt_process`,  my understanding it is a async call to proccess in  another thread, how the result returned immediately like sync?

```ruby
#web/rmt_service.rb
    put '/agents' do
      agent_setting = load_body.map do |setting|
        setting.each_with_object({}) { |pair, r| r[pair[0].to_sym] = pair[1] }
      end
      result = invoke_on_rmt_process do |_trading_context, _queue|   <------here, why get result immediately
        rmt.update_agent_setting(agent_setting)
      end
      ok(result)
    end
```

**Comment by unageanu** [comment]
`invoke_on_rmt_process` executes the block by another thread and wait for the result.

https://github.com/unageanu/jiji2/blob/e1b5c6316e3c222b77d3c87b7b21a4098ae2d2d2/src/jiji/web/services/abstract_service.rb

**Comment by janckerchen** [comment]
I look around and found  queue.pop is sync call,  waiting something push in queue.
