### ISSUE TITLE
Rake spec  should include sample_agents/spec

### ISSUE THREAD

**Issue by janckerchen** [unageanu/jiji2#390]
Rt

**Comment by unageanu** [comment]
Since `rake spec` executes specs in `spec` and `sample_agents/spec` directory, please use this.
```
$ bundle exec  rake spec
```

**Comment by janckerchen** [comment]
no, it won't.   Default --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb  doesnt match  sample_agent/spec/...

```
(I delete spec/,  sample_agent/spec not found by default)
16:57 $ bundle exec rake spec
/Users/jason/.rbenv/versions/2.2.3/bin/ruby -I/Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.2/lib:/Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-support-3.5.0/lib /Users/jason/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.5.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb -I src -I spec -I sample_agents/src -I sample_agents/spec --color -fdoc
No examples found.

Finished in 0.00047 seconds (files took 0.07798 seconds to load)
0 examples, 0 failures
```

**Comment by unageanu** [comment]
Sorry, I misunderstood the default value of `pattern`. Certainly, it is not be included.  It seems necessary to specify pattern in Rakefile, as you pointed out.

**Comment by unageanu** [comment]
I added the pattern setting to `Rakefile` in following commit, please try it.
https://github.com/unageanu/jiji2/commit/d7bff9d07a28767ae14b6382fa786f7163131c1d
