### ISSUE TITLE
現在の足のN本前から（N+M）本前までの期間Mの移動平均求める方法

### ISSUE THREAD

**Issue by t20oknw** [unageanu/jiji2#405]
現在の足のN本前から（N+M）本前までの期間Mの移動平均を求める方法を教えて下さい。
①エージェントに置いてあるsignals.rbを修正してみましたが、ビルドインのsigals.rbが動作しているようで修正が反映されません。
②方法は何でもよいので他の方法があれば教えてください。

**Comment by unageanu** [comment]
②について、組み込みのライブラリを利用して算出できます。
1. コンストラクタで平均する期間(M)を指定して `Signals::MovingAverage` のインスタンスを作成
2. あとは `Signals::MovingAverage#next_data` を、N～N+M の期間の価格データを順に指定して呼び出せば、最後にN～N+M の期間の移動平均値が返されます。

```ruby
m = 25 # Mは25とする。これにより、#next_data で指定された最新25件のデータを使用した移動平均値を返すようになる
prices = [...] # N～N+M の期間の価格データの配列が格納されているものとする

mv_n_to_m = nil
ma = Signals::MovingAverage.new(m) # M足の移動平均を算出する設定で作成
prices.each do |price|
  mv_n_to_m = ma.next_data(price) 
end

logger.info mv_n_to_m # N～N+M の期間の移動平均値
```

①について、 `signals.rb` の変更は反映されるはずです。

**Comment by t20oknw** [comment]
②について確認できました。渡すデータの方でN～N+M の期間を編集するということですね。
①については、/app/jiji2/src/jiji/model/agents/builtin_filesのsignals.rb を直接更新して再起動すると反映できました。エージェントに置いてあるsignals.rbを変更してもやはり反映されませんでした。
目的は達成したので、ありがとうございました。
