### ISSUE TITLE
Can you support an agent in simple ruby file instead of text in mongo

### ISSUE THREAD

**Issue by janckerchen** [unageanu/jiji2#409]
AgentSource will create agent source in db, it's very hard to debug or trace when agent grows up.

how can I  just add a simple ruby file include agents to codebase, so can debug step by step?

**Comment by unageanu** [comment]
I am using unit testing by rspec. by using [Utils::AgentRunner](https://github.com/unageanu/jiji2/blob/master/sample_agents/spec/utils/agent_runner.rb) , we are executing an agent in local ruby file on test spec. 
please see below test spec, this is test spec for `range_break_agent` 
https://github.com/unageanu/jiji2/blob/master/sample_agents/spec/range_break_agent_spec.rb
