### ISSUE TITLE
初期設定：証券会社の設定 でエラー

### ISSUE THREAD

**Issue by sukehisa** [unageanu/jiji2#506]
はじめまして、非常に面白そう!と思い、試してみたのですが、下記エラー出ました。
お知恵をいただければと思います。

■事象
・初期設定で、「証券会社の設定」が完了しません
デモ口座で試しており、発行されたPersonal Access Tokenを設定しましたが、この画像のようなメッセージが出て、設定が完了しませんでした。

![image](https://user-images.githubusercontent.com/1070111/52552091-5d43c900-2e22-11e9-9a8a-bd40035e0c7b.png)
![image](https://user-images.githubusercontent.com/1070111/52552321-1b675280-2e23-11e9-8dc4-9b567d374665.png)

$ docker logs jiji_jiji で確認すると下記エラーが無限にでています

> E, [2019-02-11T08:40:36.324927 #1] ERROR -- : Jiji::Errors::NotInitializedException (Jiji::Errors::NotInitializedException)
> /app/jiji2/src/jiji/errors/errors.rb:77:in `not_initialized'
> /app/jiji2/src/jiji/model/securities/nil_securities.rb:9:in `method_missing'
> /app/jiji2/src/jiji/model/trading/brokers/abstract_broker.rb:30:in `tick'
> /app/jiji2/src/jiji/model/trading/brokers/abstract_broker.rb:154:in `refresh'
> /app/jiji2/src/jiji/model/trading/jobs/notify_next_tick_job.rb:20:in `before_do_next'
> /app/jiji2/src/jiji/model/trading/jobs/notify_next_tick_job.rb:14:in `exec'
> /app/jiji2/src/jiji/model/trading/process.rb:35:in `do_next_job'
> /app/jiji2/src/jiji/model/trading/process.rb:28:in `run'
> /app/jiji2/src/jiji/model/trading/process.rb:22:in `block in start'
> /usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
> /usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
> /usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
> /usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'

■環境
ローカルのDockerにて試してみています、SSL無しの方です（docker-compose-without-ssl.yml）
・http://jiji2.unageanu.net/install/020300_install_server_to_docker.html
・Docker Desktop for Mac
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01
git version 2.15.1

・jiji_jiji　内からoanda.jpに疎通はできているようです
$ wget www.oanda.jp
は正常にhtmlを取得.

**Comment by unageanu** [comment]
はじめまして。
考えられる要因としては以下がありますが、最近作成したデモアカウントで最新のJijiを使用していれば問題ないはずです。

- 古いJiji(version 1.1.x 以前)で、新しいOanda v20 アカウントのトークンを使用している
- 新しいJiji(version 1.2.0 以降)で、古いOanda v1 アカウントのトークンを使用している

アクセストークンを設定してエラーが発生した直後のdockerのログに何か出力されていませんでしょうか?

```
$ docker-compose logs --tail 500 -f jiji
```

**Comment by sukehisa** [comment]
@unageanu さん
ありがとうございます。解決しました！
このパターンでした
` 新しいJiji(version 1.2.0 以降)で、古いOanda v1 アカウントのトークンを使用している`

新規にデモ口座を開設し、設定が無事完了しました。
（昔に作っていたデモ口座アカウントは、API v1固定になっていたんですね。。）

v20のマークがアカウント情報に出る
![image](https://user-images.githubusercontent.com/1070111/52555034-f3302180-2e2b-11e9-96d3-5d29a7f00f14.png)
↓
![image](https://user-images.githubusercontent.com/1070111/52555066-0642f180-2e2c-11e9-94b0-4df06b7df858.png)
