### ISSUE TITLE
Docker for WindowsでOANDAに接続できない

### ISSUE THREAD

**Issue by SIREN-Fuu** [unageanu/jiji2#509]
貴重なProjectありがとうございます。

暫くUbuntu上のDockerで動かしていましたが、Docker for Windows上で動くとリソースの関係で恩恵があるので、試行錯誤しています。

Docker上でコンテナは正常に動いていますが、
OANDAのアクセストークンを入力しても、データが見つかりません。となってしまいます。
コンテナに入ってapt updateやpingを外に向けて飛ばしてみると正常に動作するので、
ネットワークの問題でないと思っていますが、どうしてもOANDAと通信できないみたいです。
アクセストークンに関してはLinux上のDockerで登録できているので問題ないと思います。

何故動かないのか分かることがありましたら教えてください。

ログは以下のようになっています。
E, [2019-09-15T05:42:27.579185 #1] ERROR -- : Jiji::Errors::NotInitializedException (Jiji::Errors::NotInitializedException)
/app/jiji2/src/jiji/errors/errors.rb:77:in `not_initialized'
/app/jiji2/src/jiji/model/securities/nil_securities.rb:9:in `method_missing'
/app/jiji2/src/jiji/model/trading/brokers/abstract_broker.rb:30:in `tick'
/app/jiji2/src/jiji/model/trading/brokers/abstract_broker.rb:154:in `refresh'
/app/jiji2/src/jiji/model/trading/jobs/notify_next_tick_job.rb:20:in `before_do_next'
/app/jiji2/src/jiji/model/trading/jobs/notify_next_tick_job.rb:14:in `exec'
/app/jiji2/src/jiji/model/trading/process.rb:35:in `do_next_job'
/app/jiji2/src/jiji/model/trading/process.rb:28:in `run'
/app/jiji2/src/jiji/model/trading/process.rb:22:in `block in start'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:67:in `execute'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:405:in `block (2 levels) in spawn_thread'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:372:in `loop'
/usr/local/bundle/gems/thread-0.2.2/lib/thread/pool.rb:372:in `block in spawn_thread'

**Comment by unageanu** [comment]
初めまして。こちらのエラーは、アクセストークンの設定が完了していないときにでるものですので、初期設定がうまくできていないように見受けられます。このアクセスログからではこれ以上は何とも言えないので、追加の情報を頂ければ何かわかるかもしれません。

**Comment by SIREN-Fuu** [comment]
返信ありがとうございます。
Dockerhubにあるv1.1.2のコンテナをpullしたところ、証券会社の登録が正常に完了したので、
Docker for Windowsの環境には問題なさそうという結論になりました。

並行して他のIssueでデモ口座がV1に固定されたままになっているとの情報があったので、
デモ口座でV20のアクセストークンが取得できていないことが主問題でした。
この度は大変お騒がせ致しました。
