### ISSUE TITLE
Androidからアクセスできない

### ISSUE THREAD

**Issue by SIREN-Fuu** [unageanu/jiji2#72]
プログラムの問題ではないのかもしれませんが教えてください。
どうやってもAndroidからアクセスできないです。

ローカル端末のVMwareの中にUbuntuを入れ、各種設定して
ローカル上の別のWindowsマシンやWIFI上のApple系端末からはWebブラウザでアクセスできましたが、
何故かAndroid端末からアクセスできないです。
アクセス端末はAndroid 4.1.2の端末と4.4.2の端末でブラウザからアクセスを試みましたが
アクセスできませんでした。

SSLは無しでテストしていますが、有りでも動作端末ではちゃんと動作しました。

何かご存じのことがありましたら御教授お願いしたいです。

**Comment by unageanu** [comment]
すみません、特に心当たりはありません。

WIFI上のApple系端末からはアクセスできるのであれば、VMwareがらみのサーバー側のネットワーク設定は問題なさそうですね。このあたりが一番はまりどころだと思ったのですが。

エラーの内容(サーバーが見つからない ..etc..)などあれば、教えていただけると何かわかるかもしれません。

ちなみに、私も、ローカル端末(Windows)のVirtualBoxにCentOSを入れて使う形で動作させていますが、Android端末から特に問題なく利用できています。

**Comment by SIREN-Fuu** [comment]
お返事ありがとうございます。

その後、無事に繋がるようになりましたが、正直何故繋がったのかも原因は不明です。
たまたまUbuntuでufwを無効化した状態で、
6時間後くらいに試したら繋がりましたが、その間VMwareもルータもAndroidも触っておらず
突然繋がるようになったので、自己取得SSL有でも接続できるようになりました。

2台のAndroidが無事に接続できるようになったので
もしやAndroidはIP直接叩いてもサーバの存在を認識するのが遅いか、ufwを無効化したことによって何かのポートで通信が成功して、接続できるようになったのではないかと考えました。

ありがとうございました。

**Comment by unageanu** [comment]
無事接続できたようで、何よりです。
