### ISSUE TITLE
jiji1の頃にありましたjiji_pluginで拡張されていたsbi等はjiji2で動くのでしょうか？

### ISSUE THREAD

**Issue by hitoshi-t-pepe3** [unageanu/jiji2#89]
突然すみません。お手すきの際で良いので確認させて下さい。
Issuesというか質問なのですが、表題の件ですが動くのでしょうか。

**Comment by unageanu** [comment]
すみません、動作しません。
Jiji2はOANDA JapanのAPIでのみ動作します。

正式公開されているAPIの方が高機能で安定していること、また、証券会社によっては利用規約に照らしてグレーなところもあったため、全面的にOANDA JapanのAPIを利用する形に移行しました。指値・逆指値の注文ができたり、裁量で作成したポジションをJijiで管理できるなど、APIを利用することでできることは増えていますので、こちらのご利用をお勧めします。

**Comment by hitoshi-t-pepe3** [comment]
なるほど、無理にSBIの以前のpluginより、OANDA  Japan APIの方が良さそうですね。
了解です。ご回答ありがとうございます。
